import "./globals.css";
import Providers from "../redux/providers";
import GlobalClientLayout from "../components/GlobalClientLayout";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Coshot Admin",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Providers>
          <ToastContainer />
          <GlobalClientLayout>
            {children}
          </GlobalClientLayout>
        </Providers>
      </body>
    </html >
  );
}
